apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: cfcontainerization/cf-operator
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: cf-operator
      chartPath: deploy/helm/cf-operator
      namespace: scf
      setValueTemplates:
        image.tag: "{{ .DIGEST }}"
      wait: true
