apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-manifest
data:
  manifest: |
    name: cf-deployment
    instance_groups:
    - name: diego-cell
      instances: 3
    - name: api
      instances: 2
      jobs:
      - name: cloud_controller_ng
        properties:
          router:
            route_services_secret: "((router_route_services_secret))"
    - name: mysql
    variables:
    - name: router_route_services_secret
      type: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-ops
data:
  ops: |
    - type: replace
      path: /instance_groups/name=diego-cell?/instances
      value: 4

---
apiVersion: v1
kind: Secret
metadata:
  name: bosh-ops-secret
type: Opaque
stringData:
  ops: |
    - type: replace
      path: /instance_groups/name=diego-cell?/instances
      value: 5
---
apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: example-boshdeployment
spec:
  manifest:
    type: "configmap"
    ref: "bosh-manifest"
  ops:
    - type: "configmap"
      ref: "bosh-ops"
    - type: "secret"
      ref: "bosh-ops-secret"
