apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extendedstatefulsets.fissile.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: fissile.cloudfoundry.org
  names:
    kind: ExtendedStatefulSet
    listKind: ExtendedStatefulSetList
    plural: extendedstatefulsets
    singular: extendedstatefulset
  scope: Namespaced
  version: v1alpha1
