{{- if (include "cf-operator.singleNamespace.create" .) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ template "cf-operator.singleNamespace.name" . }}"
  labels:
    quarks.cloudfoundry.org/monitored: {{ .Values.global.monitoredID }}
    quarks.cloudfoundry.org/qjob-service-account: {{ index .Values "quarks-job" "persistOutputClusterRole" "name" }}
{{- end }}
