apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: example-boshdeployment
spec:
  manifest-ref: "bosh-manifest"
  ops-ref: "bosh-ops"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-manifest
data:
  manifest: |
    instance-groups:
      - name: diego
        instances: 3
      - name: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-ops
data:
  ops: |
    - type: replace
      path: /instance-groups/name=diego?/instances
      value: 4
